  /******************************************************************************
 *
 * [FILE NAME]: <Port_PBcfg.c>
 *
 * [AUTHOR]: <Ziad Ayman>
 *
 * [DATE CREATED]: <03/11/2022>
 *
 * [DESCRIPTION]: <Source file for Post Compile Confg>
 *
 *******************************************************************************/


/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION (1U)
#define PORT_PBCFG_SW_MINOR_VERSION (0U)
#define PORT_PBCFG_SW_PATCH_VERSION (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION (3U)

#include "Port.h"

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION) || (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION) || (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION) || (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION) || (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
                                             PortConf_PORTA_ID,PortConf_PORTA_PIN0_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTA_ID,PortConf_PORTA_PIN1_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTA_ID,PortConf_PORTA_PIN2_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTA_ID,PortConf_PORTA_PIN3_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTA_ID,PortConf_PORTA_PIN4_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTA_ID,PortConf_PORTA_PIN5_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTA_ID,PortConf_PORTA_PIN6_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTA_ID,PortConf_PORTA_PIN7_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             
                                             PortConf_PORTB_ID,PortConf_PORTB_PIN0_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTB_ID,PortConf_PORTB_PIN1_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTB_ID,PortConf_PORTB_PIN2_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTB_ID,PortConf_PORTB_PIN3_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTB_ID,PortConf_PORTB_PIN4_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTB_ID,PortConf_PORTB_PIN5_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTB_ID,PortConf_PORTB_PIN6_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTB_ID,PortConf_PORTB_PIN7_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             
                                             PortConf_PORTC_ID,PortConf_PORTC_PIN4_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTC_ID,PortConf_PORTC_PIN5_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTC_ID,PortConf_PORTC_PIN6_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTC_ID,PortConf_PORTC_PIN7_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             
                                             PortConf_PORTD_ID,PortConf_PORTD_PIN0_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTD_ID,PortConf_PORTD_PIN1_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTD_ID,PortConf_PORTD_PIN2_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTD_ID,PortConf_PORTD_PIN3_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTD_ID,PortConf_PORTD_PIN4_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTD_ID,PortConf_PORTD_PIN5_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTD_ID,PortConf_PORTD_PIN6_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTD_ID,PortConf_PORTD_PIN7_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             
                                             PortConf_PORTE_ID,PortConf_PORTE_PIN0_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTE_ID,PortConf_PORTE_PIN1_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTE_ID,PortConf_PORTE_PIN2_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTE_ID,PortConf_PORTE_PIN3_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTE_ID,PortConf_PORTE_PIN4_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTE_ID,PortConf_PORTE_PIN5_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             
                                             PortConf_PORTF_ID,PortConf_PORTF_PIN0_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTF_ID,PortConf_PORTF_PIN1_ID,PORT_PIN_OUT,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE, /*LED1 */
                                             PortConf_PORTF_ID,PortConf_PORTF_PIN2_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTF_ID,PortConf_PORTF_PIN3_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_OFF_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE,
                                             PortConf_PORTF_ID,PortConf_PORTF_PIN4_ID,PORT_PIN_IN,PORT_PIN_MODE_DIO,PORT_PIN_Level_LOW,PORT_PIN_PULL_UP_RESISTOR,PORT_PIN_DIRECTION_CHANGEABLE,PORT_PIN_MODE_CHANGEABLE    /*SW1 */
                                             
                                             
				         };

